//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 10:01:17 PM EDT 
//


package com.osbitools.ws.shared.binding.wp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentPanel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentPanel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="wwg_cont" type="{}WebWidgetContainer"/>
 *           &lt;element name="wwg_chart" type="{}WebWidgetChart"/>
 *           &lt;element name="wwg_ctrl" type="{}WebWidgetControl"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentPanel", propOrder = {
    "wwgContOrWwgChartOrWwgCtrl"
})
public class ComponentPanel {

    @XmlElements({
        @XmlElement(name = "wwg_cont", type = WebWidgetContainer.class),
        @XmlElement(name = "wwg_chart", type = WebWidgetChart.class),
        @XmlElement(name = "wwg_ctrl", type = WebWidgetControl.class)
    })
    protected List<WebWidget> wwgContOrWwgChartOrWwgCtrl;

    /**
     * Gets the value of the wwgContOrWwgChartOrWwgCtrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wwgContOrWwgChartOrWwgCtrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWwgContOrWwgChartOrWwgCtrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WebWidgetContainer }
     * {@link WebWidgetChart }
     * {@link WebWidgetControl }
     * 
     * 
     */
    public List<WebWidget> getWwgContOrWwgChartOrWwgCtrl() {
        if (wwgContOrWwgChartOrWwgCtrl == null) {
            wwgContOrWwgChartOrWwgCtrl = new ArrayList<WebWidget>();
        }
        return this.wwgContOrWwgChartOrWwgCtrl;
    }

}
