//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 10:01:17 PM EDT 
//


package com.osbitools.ws.shared.binding.wp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebPage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebPage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="panels" type="{}ComponentPanels"/>
 *       &lt;/sequence>
 *       &lt;attribute name="descr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="charset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="page_loading" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ver_max" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ver_min" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="inc" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebPage", propOrder = {
    "panels"
})
public class WebPage {

    @XmlElement(required = true)
    protected ComponentPanels panels;
    @XmlAttribute(name = "descr")
    protected String descr;
    @XmlAttribute(name = "copyright")
    protected String copyright;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "charset")
    protected String charset;
    @XmlAttribute(name = "page_loading")
    protected String pageLoading;
    @XmlAttribute(name = "ver_max", required = true)
    protected int verMax;
    @XmlAttribute(name = "ver_min", required = true)
    protected int verMin;
    @XmlAttribute(name = "inc", required = true)
    protected int inc;

    /**
     * Gets the value of the panels property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentPanels }
     *     
     */
    public ComponentPanels getPanels() {
        return panels;
    }

    /**
     * Sets the value of the panels property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentPanels }
     *     
     */
    public void setPanels(ComponentPanels value) {
        this.panels = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescr() {
        return descr;
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescr(String value) {
        this.descr = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the charset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharset() {
        return charset;
    }

    /**
     * Sets the value of the charset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharset(String value) {
        this.charset = value;
    }

    /**
     * Gets the value of the pageLoading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageLoading() {
        return pageLoading;
    }

    /**
     * Sets the value of the pageLoading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageLoading(String value) {
        this.pageLoading = value;
    }

    /**
     * Gets the value of the verMax property.
     * 
     */
    public int getVerMax() {
        return verMax;
    }

    /**
     * Sets the value of the verMax property.
     * 
     */
    public void setVerMax(int value) {
        this.verMax = value;
    }

    /**
     * Gets the value of the verMin property.
     * 
     */
    public int getVerMin() {
        return verMin;
    }

    /**
     * Sets the value of the verMin property.
     * 
     */
    public void setVerMin(int value) {
        this.verMin = value;
    }

    /**
     * Gets the value of the inc property.
     * 
     */
    public int getInc() {
        return inc;
    }

    /**
     * Sets the value of the inc property.
     * 
     */
    public void setInc(int value) {
        this.inc = value;
    }

}
