//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 10:01:17 PM EDT 
//


package com.osbitools.ws.shared.binding.wp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebWidget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebWidget">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="props" type="{}WebWidgetProperties"/>
 *         &lt;element name="prop_groups" type="{}WebWidgetPropertiesGroups" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uid" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="idx" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="class_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebWidget", propOrder = {
    "props",
    "propGroups"
})
@XmlSeeAlso({
    WebWidgetContainer.class,
    WebWidgetChart.class,
    WebWidgetControl.class
})
public class WebWidget {

    @XmlElement(required = true)
    protected WebWidgetProperties props;
    @XmlElement(name = "prop_groups")
    protected WebWidgetPropertiesGroups propGroups;
    @XmlAttribute(name = "uid", required = true)
    protected int uid;
    @XmlAttribute(name = "idx", required = true)
    protected int idx;
    @XmlAttribute(name = "class_name", required = true)
    protected String className;

    /**
     * Gets the value of the props property.
     * 
     * @return
     *     possible object is
     *     {@link WebWidgetProperties }
     *     
     */
    public WebWidgetProperties getProps() {
        return props;
    }

    /**
     * Sets the value of the props property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebWidgetProperties }
     *     
     */
    public void setProps(WebWidgetProperties value) {
        this.props = value;
    }

    /**
     * Gets the value of the propGroups property.
     * 
     * @return
     *     possible object is
     *     {@link WebWidgetPropertiesGroups }
     *     
     */
    public WebWidgetPropertiesGroups getPropGroups() {
        return propGroups;
    }

    /**
     * Sets the value of the propGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebWidgetPropertiesGroups }
     *     
     */
    public void setPropGroups(WebWidgetPropertiesGroups value) {
        this.propGroups = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     */
    public int getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     */
    public void setUid(int value) {
        this.uid = value;
    }

    /**
     * Gets the value of the idx property.
     * 
     */
    public int getIdx() {
        return idx;
    }

    /**
     * Sets the value of the idx property.
     * 
     */
    public void setIdx(int value) {
        this.idx = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

}
