//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 01:29:02 PM EDT 
//


package com.osbitools.ws.shared.binding.ll_set;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LangLabelsSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LangLabelsSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lang_label" type="{}LangLabel" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lang_list" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ver_max" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ver_min" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LangLabelsSet", propOrder = {
    "langLabel"
})
public class LangLabelsSet {

    @XmlElement(name = "lang_label", required = true)
    protected List<LangLabel> langLabel;
    @XmlAttribute(name = "lang_list")
    protected String langList;
    @XmlAttribute(name = "ver_max", required = true)
    protected int verMax;
    @XmlAttribute(name = "ver_min", required = true)
    protected int verMin;

    /**
     * Gets the value of the langLabel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the langLabel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLangLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangLabel }
     * 
     * 
     */
    public List<LangLabel> getLangLabel() {
        if (langLabel == null) {
            langLabel = new ArrayList<LangLabel>();
        }
        return this.langLabel;
    }

    /**
     * Gets the value of the langList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangList() {
        return langList;
    }

    /**
     * Sets the value of the langList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangList(String value) {
        this.langList = value;
    }

    /**
     * Gets the value of the verMax property.
     * 
     */
    public int getVerMax() {
        return verMax;
    }

    /**
     * Sets the value of the verMax property.
     * 
     */
    public void setVerMax(int value) {
        this.verMax = value;
    }

    /**
     * Gets the value of the verMin property.
     * 
     */
    public int getVerMin() {
        return verMin;
    }

    /**
     * Sets the value of the verMin property.
     * 
     */
    public void setVerMin(int value) {
        this.verMin = value;
    }

}
