//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutoIncColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AutoIncColumn">
 *   &lt;complexContent>
 *     &lt;extension base="{}Cell">
 *       &lt;attribute name="start_from" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="inc_by" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutoIncColumn")
public class AutoIncColumn
    extends Cell
{

    @XmlAttribute(name = "start_from")
    protected Integer startFrom;
    @XmlAttribute(name = "inc_by")
    protected Integer incBy;

    /**
     * Gets the value of the startFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getStartFrom() {
        if (startFrom == null) {
            return  0;
        } else {
            return startFrom;
        }
    }

    /**
     * Sets the value of the startFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartFrom(Integer value) {
        this.startFrom = value;
    }

    /**
     * Gets the value of the incBy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getIncBy() {
        if (incBy == null) {
            return  1;
        } else {
            return incBy;
        }
    }

    /**
     * Sets the value of the incBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIncBy(Integer value) {
        this.incBy = value;
    }

}
