//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CsvData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CsvData">
 *   &lt;complexContent>
 *     &lt;extension base="{}DataSetSpec">
 *       &lt;attribute name="file_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="delim" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="quote_char" type="{http://www.w3.org/2001/XMLSchema}string" default=""" />
 *       &lt;attribute name="escape_char" type="{http://www.w3.org/2001/XMLSchema}string" default="\" />
 *       &lt;attribute name="col_first_row" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CsvData")
public class CsvData
    extends DataSetSpec
{

    @XmlAttribute(name = "file_name", required = true)
    protected String fileName;
    @XmlAttribute(name = "delim")
    protected String delim;
    @XmlAttribute(name = "quote_char")
    protected String quoteChar;
    @XmlAttribute(name = "escape_char")
    protected String escapeChar;
    @XmlAttribute(name = "col_first_row")
    protected Boolean colFirstRow;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the delim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelim() {
        if (delim == null) {
            return ",";
        } else {
            return delim;
        }
    }

    /**
     * Sets the value of the delim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelim(String value) {
        this.delim = value;
    }

    /**
     * Gets the value of the quoteChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteChar() {
        if (quoteChar == null) {
            return "\"";
        } else {
            return quoteChar;
        }
    }

    /**
     * Sets the value of the quoteChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteChar(String value) {
        this.quoteChar = value;
    }

    /**
     * Gets the value of the escapeChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEscapeChar() {
        if (escapeChar == null) {
            return "\\";
        } else {
            return escapeChar;
        }
    }

    /**
     * Sets the value of the escapeChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEscapeChar(String value) {
        this.escapeChar = value;
    }

    /**
     * Gets the value of the colFirstRow property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isColFirstRow() {
        if (colFirstRow == null) {
            return true;
        } else {
            return colFirstRow;
        }
    }

    /**
     * Sets the value of the colFirstRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColFirstRow(Boolean value) {
        this.colFirstRow = value;
    }

}
