//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataSetExtList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataSetExtList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="group_ds" type="{}GroupDataSetDescr"/>
 *           &lt;element name="static_ds" type="{}StaticDataSetDescr"/>
 *           &lt;element name="csv_ds" type="{}CsvDataSetDescr"/>
 *           &lt;element name="sql_ds" type="{}SqlDataSetDescr"/>
 *           &lt;element name="xml_ds" type="{}XmlDataSetDescr"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSetExtList", propOrder = {
    "groupDsOrStaticDsOrCsvDs"
})
public class DataSetExtList {

    @XmlElements({
        @XmlElement(name = "group_ds", type = GroupDataSetDescr.class),
        @XmlElement(name = "static_ds", type = StaticDataSetDescr.class),
        @XmlElement(name = "csv_ds", type = CsvDataSetDescr.class),
        @XmlElement(name = "sql_ds", type = SqlDataSetDescr.class),
        @XmlElement(name = "xml_ds", type = XmlDataSetDescr.class)
    })
    protected List<DataSetExt> groupDsOrStaticDsOrCsvDs;

    /**
     * Gets the value of the groupDsOrStaticDsOrCsvDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupDsOrStaticDsOrCsvDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupDsOrStaticDsOrCsvDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupDataSetDescr }
     * {@link StaticDataSetDescr }
     * {@link CsvDataSetDescr }
     * {@link SqlDataSetDescr }
     * {@link XmlDataSetDescr }
     * 
     * 
     */
    public List<DataSetExt> getGroupDsOrStaticDsOrCsvDs() {
        if (groupDsOrStaticDsOrCsvDs == null) {
            groupDsOrStaticDsOrCsvDs = new ArrayList<DataSetExt>();
        }
        return this.groupDsOrStaticDsOrCsvDs;
    }

}
