//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataSetExt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataSetExt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lang_map" type="{}LangMap" minOccurs="0"/>
 *         &lt;element name="ex_columns" type="{}ExColumns" minOccurs="0"/>
 *         &lt;element name="sort_by_grp" type="{}SortGroup" minOccurs="0"/>
 *         &lt;element name="filter" type="{}ConditionFilter" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idx" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataSetExt", propOrder = {
    "langMap",
    "exColumns",
    "sortByGrp",
    "filter"
})
@XmlSeeAlso({
    DataSetDescr.class,
    CsvDataSetDescr.class,
    GroupDataSetDescr.class,
    SqlDataSetDescr.class,
    StaticDataSetDescr.class,
    XmlDataSetDescr.class
})
public class DataSetExt {

    @XmlElement(name = "lang_map")
    protected LangMap langMap;
    @XmlElement(name = "ex_columns")
    protected ExColumns exColumns;
    @XmlElement(name = "sort_by_grp")
    protected SortGroup sortByGrp;
    protected ConditionFilter filter;
    @XmlAttribute(name = "idx")
    protected Integer idx;

    /**
     * Gets the value of the langMap property.
     * 
     * @return
     *     possible object is
     *     {@link LangMap }
     *     
     */
    public LangMap getLangMap() {
        return langMap;
    }

    /**
     * Sets the value of the langMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link LangMap }
     *     
     */
    public void setLangMap(LangMap value) {
        this.langMap = value;
    }

    /**
     * Gets the value of the exColumns property.
     * 
     * @return
     *     possible object is
     *     {@link ExColumns }
     *     
     */
    public ExColumns getExColumns() {
        return exColumns;
    }

    /**
     * Sets the value of the exColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExColumns }
     *     
     */
    public void setExColumns(ExColumns value) {
        this.exColumns = value;
    }

    /**
     * Gets the value of the sortByGrp property.
     * 
     * @return
     *     possible object is
     *     {@link SortGroup }
     *     
     */
    public SortGroup getSortByGrp() {
        return sortByGrp;
    }

    /**
     * Sets the value of the sortByGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortGroup }
     *     
     */
    public void setSortByGrp(SortGroup value) {
        this.sortByGrp = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionFilter }
     *     
     */
    public ConditionFilter getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionFilter }
     *     
     */
    public void setFilter(ConditionFilter value) {
        this.filter = value;
    }

    /**
     * Gets the value of the idx property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * Sets the value of the idx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdx(Integer value) {
        this.idx = value;
    }

}
