//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupData">
 *   &lt;complexContent>
 *     &lt;extension base="{}DataSetSpec">
 *       &lt;sequence>
 *         &lt;element name="ds_list" type="{}DataSetExtList"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupData", propOrder = {
    "dsList"
})
public class GroupData
    extends DataSetSpec
{

    @XmlElement(name = "ds_list", required = true)
    protected DataSetExtList dsList;

    /**
     * Gets the value of the dsList property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetExtList }
     *     
     */
    public DataSetExtList getDsList() {
        return dsList;
    }

    /**
     * Sets the value of the dsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetExtList }
     *     
     */
    public void setDsList(DataSetExtList value) {
        this.dsList = value;
    }

}
