//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.osbitools.ws.shared.binding.ds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ds_QNAME = new QName("", "ds");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.osbitools.ws.shared.binding.ds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSetDescr }
     * 
     */
    public DataSetDescr createDataSetDescr() {
        return new DataSetDescr();
    }

    /**
     * Create an instance of {@link Columns }
     * 
     */
    public Columns createColumns() {
        return new Columns();
    }

    /**
     * Create an instance of {@link CsvDataSetDescr }
     * 
     */
    public CsvDataSetDescr createCsvDataSetDescr() {
        return new CsvDataSetDescr();
    }

    /**
     * Create an instance of {@link Cell }
     * 
     */
    public Cell createCell() {
        return new Cell();
    }

    /**
     * Create an instance of {@link GroupDataSetDescr }
     * 
     */
    public GroupDataSetDescr createGroupDataSetDescr() {
        return new GroupDataSetDescr();
    }

    /**
     * Create an instance of {@link ConditionFilter }
     * 
     */
    public ConditionFilter createConditionFilter() {
        return new ConditionFilter();
    }

    /**
     * Create an instance of {@link SqlParameter }
     * 
     */
    public SqlParameter createSqlParameter() {
        return new SqlParameter();
    }

    /**
     * Create an instance of {@link DataSetSpec }
     * 
     */
    public DataSetSpec createDataSetSpec() {
        return new DataSetSpec();
    }

    /**
     * Create an instance of {@link RequestParameters }
     * 
     */
    public RequestParameters createRequestParameters() {
        return new RequestParameters();
    }

    /**
     * Create an instance of {@link LangColumn }
     * 
     */
    public LangColumn createLangColumn() {
        return new LangColumn();
    }

    /**
     * Create an instance of {@link OrderedList }
     * 
     */
    public OrderedList createOrderedList() {
        return new OrderedList();
    }

    /**
     * Create an instance of {@link CalcColumns }
     * 
     */
    public CalcColumns createCalcColumns() {
        return new CalcColumns();
    }

    /**
     * Create an instance of {@link LangMap }
     * 
     */
    public LangMap createLangMap() {
        return new LangMap();
    }

    /**
     * Create an instance of {@link SqlDataSetDescr }
     * 
     */
    public SqlDataSetDescr createSqlDataSetDescr() {
        return new SqlDataSetDescr();
    }

    /**
     * Create an instance of {@link CsvData }
     * 
     */
    public CsvData createCsvData() {
        return new CsvData();
    }

    /**
     * Create an instance of {@link ColumnHeader }
     * 
     */
    public ColumnHeader createColumnHeader() {
        return new ColumnHeader();
    }

    /**
     * Create an instance of {@link RequestParameter }
     * 
     */
    public RequestParameter createRequestParameter() {
        return new RequestParameter();
    }

    /**
     * Create an instance of {@link AutoIncColumn }
     * 
     */
    public AutoIncColumn createAutoIncColumn() {
        return new AutoIncColumn();
    }

    /**
     * Create an instance of {@link ExColumns }
     * 
     */
    public ExColumns createExColumns() {
        return new ExColumns();
    }

    /**
     * Create an instance of {@link CalcColumn }
     * 
     */
    public CalcColumn createCalcColumn() {
        return new CalcColumn();
    }

    /**
     * Create an instance of {@link AutoIncColumns }
     * 
     */
    public AutoIncColumns createAutoIncColumns() {
        return new AutoIncColumns();
    }

    /**
     * Create an instance of {@link RowDef }
     * 
     */
    public RowDef createRowDef() {
        return new RowDef();
    }

    /**
     * Create an instance of {@link StaticData }
     * 
     */
    public StaticData createStaticData() {
        return new StaticData();
    }

    /**
     * Create an instance of {@link SortCond }
     * 
     */
    public SortCond createSortCond() {
        return new SortCond();
    }

    /**
     * Create an instance of {@link DataSetExtList }
     * 
     */
    public DataSetExtList createDataSetExtList() {
        return new DataSetExtList();
    }

    /**
     * Create an instance of {@link StaticDataSetDescr }
     * 
     */
    public StaticDataSetDescr createStaticDataSetDescr() {
        return new StaticDataSetDescr();
    }

    /**
     * Create an instance of {@link DataSetExt }
     * 
     */
    public DataSetExt createDataSetExt() {
        return new DataSetExt();
    }

    /**
     * Create an instance of {@link SortGroup }
     * 
     */
    public SortGroup createSortGroup() {
        return new SortGroup();
    }

    /**
     * Create an instance of {@link XmlData }
     * 
     */
    public XmlData createXmlData() {
        return new XmlData();
    }

    /**
     * Create an instance of {@link GroupData }
     * 
     */
    public GroupData createGroupData() {
        return new GroupData();
    }

    /**
     * Create an instance of {@link SqlParameters }
     * 
     */
    public SqlParameters createSqlParameters() {
        return new SqlParameters();
    }

    /**
     * Create an instance of {@link XmlDataSetDescr }
     * 
     */
    public XmlDataSetDescr createXmlDataSetDescr() {
        return new XmlDataSetDescr();
    }

    /**
     * Create an instance of {@link RowCell }
     * 
     */
    public RowCell createRowCell() {
        return new RowCell();
    }

    /**
     * Create an instance of {@link StaticRecords }
     * 
     */
    public StaticRecords createStaticRecords() {
        return new StaticRecords();
    }

    /**
     * Create an instance of {@link SqlData }
     * 
     */
    public SqlData createSqlData() {
        return new SqlData();
    }

    /**
     * Create an instance of {@link SqlDef }
     * 
     */
    public SqlDef createSqlDef() {
        return new SqlDef();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSetDescr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ds")
    public JAXBElement<DataSetDescr> createDs(DataSetDescr value) {
        return new JAXBElement<DataSetDescr>(_Ds_QNAME, DataSetDescr.class, null, value);
    }

}
