//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SortCond complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SortCond">
 *   &lt;complexContent>
 *     &lt;extension base="{}OrderedList">
 *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sequence" type="{}SortTypes" default="asc" />
 *       &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="str_sort" type="{}StringSort" default="natural" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SortCond")
public class SortCond
    extends OrderedList
{

    @XmlAttribute(name = "column", required = true)
    protected String column;
    @XmlAttribute(name = "sequence")
    protected SortTypes sequence;
    @XmlAttribute(name = "unique")
    protected Boolean unique;
    @XmlAttribute(name = "str_sort")
    protected StringSort strSort;

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link SortTypes }
     *     
     */
    public SortTypes getSequence() {
        if (sequence == null) {
            return SortTypes.ASC;
        } else {
            return sequence;
        }
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortTypes }
     *     
     */
    public void setSequence(SortTypes value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the unique property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUnique() {
        if (unique == null) {
            return false;
        } else {
            return unique;
        }
    }

    /**
     * Sets the value of the unique property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnique(Boolean value) {
        this.unique = value;
    }

    /**
     * Gets the value of the strSort property.
     * 
     * @return
     *     possible object is
     *     {@link StringSort }
     *     
     */
    public StringSort getStrSort() {
        if (strSort == null) {
            return StringSort.NATURAL;
        } else {
            return strSort;
        }
    }

    /**
     * Sets the value of the strSort property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringSort }
     *     
     */
    public void setStrSort(StringSort value) {
        this.strSort = value;
    }

}
