//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SqlDataSetDescr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SqlDataSetDescr">
 *   &lt;complexContent>
 *     &lt;extension base="{}DataSetExt">
 *       &lt;sequence>
 *         &lt;element name="sql_data" type="{}SqlData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SqlDataSetDescr", propOrder = {
    "sqlData"
})
public class SqlDataSetDescr
    extends DataSetExt
{

    @XmlElement(name = "sql_data", required = true)
    protected SqlData sqlData;

    /**
     * Gets the value of the sqlData property.
     * 
     * @return
     *     possible object is
     *     {@link SqlData }
     *     
     */
    public SqlData getSqlData() {
        return sqlData;
    }

    /**
     * Sets the value of the sqlData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlData }
     *     
     */
    public void setSqlData(SqlData value) {
        this.sqlData = value;
    }

}
