//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StaticData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StaticData">
 *   &lt;complexContent>
 *     &lt;extension base="{}DataSetSpec">
 *       &lt;sequence>
 *         &lt;element name="static_rows" type="{}StaticRecords"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StaticData", propOrder = {
    "staticRows"
})
public class StaticData
    extends DataSetSpec
{

    @XmlElement(name = "static_rows", required = true)
    protected StaticRecords staticRows;

    /**
     * Gets the value of the staticRows property.
     * 
     * @return
     *     possible object is
     *     {@link StaticRecords }
     *     
     */
    public StaticRecords getStaticRows() {
        return staticRows;
    }

    /**
     * Sets the value of the staticRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticRecords }
     *     
     */
    public void setStaticRows(StaticRecords value) {
        this.staticRows = value;
    }

}
