//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 01:35:19 AM EDT 
//


package com.osbitools.ws.shared.binding.ds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StaticDataSetDescr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StaticDataSetDescr">
 *   &lt;complexContent>
 *     &lt;extension base="{}DataSetExt">
 *       &lt;sequence>
 *         &lt;element name="static_data" type="{}StaticData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StaticDataSetDescr", propOrder = {
    "staticData"
})
public class StaticDataSetDescr
    extends DataSetExt
{

    @XmlElement(name = "static_data", required = true)
    protected StaticData staticData;

    /**
     * Gets the value of the staticData property.
     * 
     * @return
     *     possible object is
     *     {@link StaticData }
     *     
     */
    public StaticData getStaticData() {
        return staticData;
    }

    /**
     * Sets the value of the staticData property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticData }
     *     
     */
    public void setStaticData(StaticData value) {
        this.staticData = value;
    }

}
